# Generated by Django 3.2 on 2021-07-16 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categrory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='thredType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thred_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('weight', models.CharField(max_length=50)),
                ('dimensions', models.CharField(max_length=50)),
                ('age_Group', models.CharField(max_length=100)),
                ('decription', models.TextField()),
                ('main_Img', models.ImageField(default='', upload_to='myApp/images')),
                ('img1', models.ImageField(default='', upload_to='myApp/images')),
                ('img2', models.ImageField(default='', upload_to='myApp/images')),
                ('img3', models.ImageField(default='', upload_to='myApp/images')),
                ('img4', models.ImageField(default='', upload_to='myApp/images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopMart.categrory')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopMart.color')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopMart.material')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopMart.shape')),
                ('thread_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopMart.thredtype')),
            ],
        ),
    ]
