# Generated by Django 3.2 on 2021-07-19 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopMart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propertie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.CharField(max_length=50)),
                ('c', models.CharField(max_length=20)),
                ('s', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopMart.propertie')),
            ],
        ),
    ]
