# Generated by Django 3.2 on 2021-07-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopMart', '0002_new_propertie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='prop',
        ),
        migrations.RenameField(
            model_name='categrory',
            old_name='category_Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='color_Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='age_Group',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thread_Type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateField(default='2021-07-20'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_decription',
            field=models.CharField(default='hdhdhdh', max_length=600),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='New',
        ),
        migrations.DeleteModel(
            name='Propertie',
        ),
        migrations.DeleteModel(
            name='Shape',
        ),
        migrations.DeleteModel(
            name='thredType',
        ),
    ]
